#ifndef _VC_MIPI_COMMON_H
#define _VC_MIPI_COMMON_H

#include "vc_mipi_core.h"

// /*............. Sensor models */
// enum sen_model {
//     SEN_MODEL_UNKNOWN = 0,
//     OV7251_MODEL_MONOCHROME,
//     OV7251_MODEL_COLOR,
// //    OV9281_MODEL,
//     OV9281_MODEL_MONOCHROME,
//     OV9281_MODEL_COLOR,

//     IMX183_MODEL_MONOCHROME,
//     IMX183_MODEL_COLOR,
//     IMX226_MODEL_MONOCHROME,
//     IMX226_MODEL_COLOR,
//     IMX250_MODEL_MONOCHROME,
//     IMX250_MODEL_COLOR,
//     IMX252_MODEL_MONOCHROME,
//     IMX252_MODEL_COLOR,
//     IMX273_MODEL_MONOCHROME,
//     IMX273_MODEL_COLOR,

//     IMX290_MODEL_MONOCHROME,
//     IMX290_MODEL_COLOR,
//     IMX296_MODEL_MONOCHROME,
//     IMX296_MODEL_COLOR,
//     IMX297_MODEL_MONOCHROME,
//     IMX297_MODEL_COLOR,

//     IMX327C_MODEL,
//     IMX327_MODEL_MONOCHROME,
//     IMX327_MODEL_COLOR,
//     IMX412_MODEL_MONOCHROME,
//     IMX412_MODEL_COLOR,
//     IMX415_MODEL_MONOCHROME,
//     IMX415_MODEL_COLOR,
// };

#endif // _VC_MIPI_COMMON_H